### ISSUE TITLE
Footer edit review

### ISSUE THREAD

**Issue by gumityolcu** [complex-systems-turkey/complex-systems-turkey.github.io#1]
I opened a branch called footer. I did some edits on the footer. Please give feedback.

You can see the improvements with:

bundle exec jekyll b

bundle exec jekyll serve

**Comment by okyksl** [comment]
Couple of things:

- [x] Footer still overlaps with content on small screen resolutions. 
- [x] Should we type down contact and address information in the footer? I think at least the event location should be highlighted somewhere else -> just before the apply button in overview page?
- [x] Maybe we can move source links to the right side and leave center open. I'm not fan of current footer visually -- especially considering we can't fill the full page yet. But, we can deal with this later.

**Comment by gumityolcu** [comment]
We decided to remove footer and refer to hillhacks on the index page
